trigger:
- master
- feature/*

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Download ShiftLeft cli
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile $(Agent.HomeDirectory)\sl.zip
      Expand-Archive -Path $(Agent.HomeDirectory)\sl.zip -DestinationPath $(Agent.HomeDirectory)\
- task: CmdLine@2
  displayName: Analyze with Inspect
  inputs:
    script: |
      $(Agent.HomeDirectory)\sl analyze --verbose --no-diagnostic --force --version-id 1 --app ShiftLeftPythonAzWin branch=$(Build.SourceBranchName) --python $(Build.SourcesDirectory)
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    SHIFTLEFT_ORG_ID: $(SHIFTLEFT_ORG_ID)
    SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)
    SHIFTLEFT_API_TOKEN: $(SHIFTLEFT_API_TOKEN)
