variables:
- group: shiftleft-token

pool:
  vmImage: 'ubuntu-latest'
container: shiftleft/scan-java:latest
steps:
- task: CmdLine@2
  displayName: Analyze with Inspect
  inputs:
    script: |      
      sl scan --verbose --no-diagnostic --force --app ShiftLeftPythonAz branch=$(Build.SourceBranchName) --type=python $(Build.SourcesDirectory)
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    SHIFTLEFT_ORG_ID: $(SHIFTLEFT_ORG_ID)
    SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)
    SHIFTLEFT_API_TOKEN: $(SHIFTLEFT_API_TOKEN)
